site_name: UI Documentation

pages:
	- Tutorial:
		- before we start
		- overview
		- step 1
		- step 1
		- step 3
	- Installation:
		- set up monster ui
		- set up monster apps
	- Quick Start:
		- provision database (appstore)
		- form validation (validation)
		- make requests (api)

		- file structure
		- rendering templates
	- Advanced Guides:
		- templates in depth (handlebars)
		- context (flags)
		- common controls (commonControls)
		- handling translation (internationalization)
		- subscription hooks (events)

		- submodules
		- external requests
		- websockets
	- Contributing:
		- set up linter (linting)
		- coding standars:
			- index (codingStandards)
			- javascript (javascriptStleGuide)
	- References:
		- core methods:
			- monster (monster)
			- monster.ui (ui)
			- monster.util (util)
		- kazoo sdk (kazooSdk)
		- build system (gulpCommand)
		- using postman (using-postman-as-a-crud)
